config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :restaurants, only: [:index, :show] do
    resources :comments, only: [:create, :destroy]

    collection do
      get :feeds
    end
    member do
      get :dashboard
    end
  end
  resources :categories, only: :show
  resources :users, only: [:show, :edit, :update]
  namespace :admin do
    resources :restaurants
    resources :categories
  end
  root "restaurants#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants, dependent: :restrict_with_error
  validates_presence_of :name
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  #mount_uploader :image, PhotoUploader
  validates_presence_of :name
  belongs_to :category, optional: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :restrict_with_error
  has_many :restaurants, through: :comments
  mount_uploader :avatar, AvatarUploader

  def admin?
    self.role == "admin"
  end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :authenticate_admin
  private
  def authenticate_admin
    unless current_user.admin?
      flash[:alert] = "Not allow"
      redirect_to root_path
    end
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_action :set_category, only: [:update, :destroy]
  def index
    @categories = Category.all
    if params[:id]
      set_category
    else
      @category = Category.new
    end

  end
  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "成功建立類別"
      redirect_to admin_categories_path
    else
      @categories = Category.all
      render :index
    end
  end
  def update
    if @category.update(category_params)
      redirect_to admin_categories_path
      flash[:notice] = "category was successfully updated"
    else
      @category = Category.all
      render :index
    end
  end
  def destroy
    @category.destroy
    flash[:alert] = "category was sucessfully deleted"
    redirect_to admin_categories_path
  end
  private
  def category_params
    params.require(:category).permit(:name)
  end
  def set_category
    @category = Category.find(params[:id])
  end
end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseController

  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]
  def index
    @restaurants = Restaurant.page(params[:page]).per(10)
  end
  def new
    @restaurant = Restaurant.new
  end
  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "餐廳成功建立"
      redirect_to admin_restaurants_path
    else
      flash[:alert] = "餐廳建立失敗"
      render :new
    end
  end
  def show
  end
  def edit
  end
  def update
    if @restaurant.update(restaurant_params)
      flashp[:notice] = "餐廳資料修改成功"
      redirect_to admin_restaurants_path
    else
      flash[:alert] = "餐廳資料修改失敗"
      render :edit
    end
  end
  def destroy
    if @restaurant.destroy
      flash[:notice] = "餐廳刪除成功"
      redirect_to admin_restaurants_path
    else
      flash[:alert] = "餐廳無法刪除"
    end
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :tel, :address, :opening_hours, :description, :image)
  end
  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!


end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @restaurant= Restaurant.find(params[:restaurant_id])
    @comment = @restaurant.comments.build(comment_params)
    @comment.user = current_user
    @comment.save!
    redirect_to restaurant_path(@restaurant)
  end
  def destroy
    @restaurant = Restaurant.find(params[:restaurant_id])
    @comment = Comment.find(params[:id])
    if current_user.admin?
      @comment.destroy
      redirect_to restaurant_path(@restaurant)
    end
  end
  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end
  def show
    @restaurant = Restaurant.find(params[:id])
    @comment = Comment.new
  end
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def show
    @user = User.find(params[:id])
    @commented_restaurants = @user.restaurants.uniq
  end
  def edit
    unless @user == current_user
      redirect_to user_path(@user)
    end
  end
  def update
    @user.update(user_params)
    redirect_to user_path(@user)
  end
  private
  def set_user
    @user = User.find(params[:id])
  end
  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>

  <div class="row">

    <div class="col-md-12">
      <div>
        <%= link_to 'Restaurant', admin_restaurants_path %> |
        <%= link_to 'Categories', admin_categories_path %>
      </div>
      <br>

      <div class="form-inline" >
        <%= form_for [:admin, @category] do |f| %>
            <div class="form-group">
              <%= f.text_field :name, placeholder: "Category Name",  class: "form-control" %>
            </div>
            <%= f.submit class: "btn btn-primary" %>
            <% if @category.errors.any? %>
                <%= @category.errors.full_messages.to_sentence %>
            <% end %>
        <% end %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>#</th>
          <th>Category Name</th>
          <th>#</th>
        </tr>
        </thead>
        <tbody>
        <% @categories.each do |category| %>
            <tr>
              <th scope="row"><%= category.id %></th>
              <td><%= category.name %></td>
              <td><%= link_to 'Edit', admin_categories_path(id: category.id) %>
                  <%= link_to 'Delete', admin_category_path(category), method: :delete, data: {confirm: "Are you sure?"} %></td>
            </tr>
        <% end %>
        </tbody>
      </table>

    </div>

  </div>
</div>

app/views/admin/restaurants/_form.html.erb
<div class="container">
  <div class="row">

    <% if @restaurant.errors.any? %>
        <h4>We have some errors here !</h4>
        <ul>
          <% @restaurant.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
          <% end %>
        </ul>
        <hr>
    <% end %>

    <%= form_for [:admin, @restaurant] do |f| %>

        <%= f.collection_select :category_id, Category.all, :id, :name, {prompt: true}, {class: "form-control"} %>

        <div class="form-group">
          <%= f.label :name, "Name" %>
          <%= f.text_field :name, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :tel, "Tel" %>
          <%= f.text_field :tel, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :address, "Address" %>
          <%= f.text_field :address, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :opening_hours, "Opening Hours" %>
          <%= f.text_field :opening_hours, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :description, "Description" %>
          <%= f.text_area :description, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= f.label :image, "Photo" %>
          <%= image_tag @restaurant.image, width: '300px' if @restaurant.image? %>
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
        </div>
    <% end %>

  </div>
</div>

app/views/admin/restaurants/edit.html.erb
<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>餐廳後台</h1>

  <div class="row">

    <div class="col-md-12">
      <div>
        <%= link_to 'Restaurant', admin_restaurants_path %> |
        <%= link_to 'Categories', admin_categories_path %>
      </div>
      <br>
      <div>
        <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
        <tr>
          <th>#</th>
          <th>Category</th>
          <th>Name</th>
          <th>#</th>
        </tr>
        </thead>
        <tbody>
        <% @restaurants.each do |restaurant| %>
            <tr>
              <th scope="row"><%= restaurant.id %></th>
              <td>[<%= restaurant.category.name %>]</td>
              <td><%= restaurant.name %></td>
              <td>
                <%= link_to 'Show', admin_restaurant_path(restaurant) %>
                <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
                <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <%= paginate @restaurants %>
      </div>

    </div>

  </div>
</div>

app/views/admin/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
    <h2>We have some errors here!</h2>
    <ul>
      <%= @restaurant.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
<% end %>

<%= form_for [:admin, @restaurant] do |f| %>
    <%= f.label :name, '店名' %>
    <%= f.text_field :name %>

    <%= f.label :tel, '電話' %>
    <%= f.text_field :tel %>

    <%= f.label :address, '地址' %>
    <%= f.text_field :address %>

    <%= f.label :opening_hours, '營業時間' %>
    <%= f.text_field :opening_hours %>

    <%= f.label :description, '描述' %>
    <%= f.text_field :description %>

    <%= f.submit  %>
<% end %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>


    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
    </div>

    <div class="clearfix"></div>

    <hr>

  </div>
</div>

<%= link_to '回到首頁', admin_restaurants_path %>

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
          <li role="presentation" , class="<%= "active" if category == @category %>"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>

    <br>

    <%= render partial: "shared/restaurant_list" %>

  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantMytest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= filestack_js_include_tag %>
    <%= filestack_js_init_tag %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">餐廳評論網</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-right">
            <% if current_user %>
                <li><%= link_to 'Profile', user_path(current_user) %></li>
                <li><%= link_to '登出', destroy_user_session_path, method: :delete %></li>
                <li><%= link_to '修改密碼', edit_user_registration_path %></li>
            <% else %>
                <li><%= link_to '登入', new_user_session_path %></li>
                <li><%= link_to '註冊', new_user_registration_path %></li>
            <% end  %>
          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <% if flash[:notice] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-success alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= notice %>
          </div>
        </div>
      </div>
  <% end %>
  <% if flash[:alert] %>
      <div class="container">
        <div class="row">
          <div class="alert alert-danger alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <%= alert %>
          </div>
        </div>
      </div>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/restaurants/dashboard.html.erb
<h1><%= @restaurant.name %>'s Dashboard</h1>
<hr>
<ul>
  <li>有 <%= @restaurant.comments.count %> 筆評論</li>
  <li>這家餐廳的平均價位為 $XXX</li>
  <li>有 XX 人收藏這家餐廳</li>
</ul>

app/views/restaurants/feeds.html.erb
<div class="container">
  <div class="row">

    <!-- 使用 Bootstrap components 的 Nav Tabs -->
    <!-- https://getbootstrap.com/docs/3.3/components/#nav-tabs -->
    <ul class="nav nav-tabs">
      <li role="presentation">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation" class="active">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
    </ul>

  </div>
</div>

<br>

<div class="container">
  <div class="row">

    <div class="col-md-10 col-md-offset-1">
      <h1>餐廳最新動態</h1>
      <hr>
      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新餐廳</div>
          <div class="panel-body">
            <% @recent_restaurants.each do |restaurant| %>
                <div>
                  <h4>
                    <%= link_to restaurant.name, restaurant_path(restaurant) %>
                    <small><%= restaurant.category.name %></small>
                  </h4>
                  <p><%= truncate(restaurant.description, length: 80) %></p>
                  <hr>
                </div>
            <% end %>
          </div>
        </div>
      </div>

      <div class="col-md-6">
        <div class="panel panel-default">
          <div class="panel-heading">最新評論</div>
          <div class="panel-body">
            <% @recent_comments.each do |comment| %>
                <div>
                  <h4>
                    <%= link_to comment.restaurant.name, restaurant_path(comment.restaurant) %>
                  </h4>
                  <p><%= truncate(comment.content, length: 80) %><small > - by <%= link_to comment.user.name, user_path(comment.user) %></small></p>
                  <hr>
                </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">

    <!-- 使用 Bootstrap components 的 Nav Tabs -->
    <!-- https://getbootstrap.com/docs/3.3/components/#nav-tabs -->
    <ul class="nav nav-tabs">
      <li role="presentation" class="active">
        <%= link_to '首頁', root_path %>
      </li>
      <li role="presentation">
        <%= link_to '最新動態', feeds_restaurants_path %>
      </li>
    </ul>

  </div>
</div>

<br>
<div class="container">
  <div class="row">
    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
          <li role="presentation"><%= link_to category.name, category_path(category) %></li>
      <% end %>
    </ul>

    <br>

    <%= render partial: "shared/restaurant_list" %>

  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <p>[<%= @restaurant.category.name %>]</p>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>
    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>
      <%= link_to 'Dashboard', dashboard_restaurant_path(@restaurant), class: "btn btn-primary" %>
    </div>

    <div class="clearfix"></div>

    <hr>

    <% @restaurant.comments.each do |comment| %>
        <div>
          <h4><%= comment.user.email.split('@').first %></h4>
          <p><%= simple_format comment.content %></p>
          <p class="text-muted">
            <em><%= time_ago_in_words(comment.created_at) %> ago - </em>
            <% if current_user.admin? %>
                <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
            <% end %>
          </p>
        </div>
        <hr>
    <% end %>

    <%= form_for [@restaurant, @comment] do |f| %>
        <div class="form-group">
          <%= f.text_area :content, placeholder: "留個言吧", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.submit class: "btn btn-primary" %>
          <%= f.button "Cancel", type: :reset, class: "btn btn-default" %>
        </div>
    <% end %>
  </div>
</div>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
    <div class="col-sm-6 col-md-4">
      <div class="restaurant-item">
        <%= image_tag restaurant.image, class: "img-responsive center-block" %>
        <div class="caption">
          <h3><%= link_to restaurant.name, restaurant_path(restaurant) %></h3>
          <p class="label label-default"><%= restaurant.category.name %><p>
          <p><%= truncate(restaurant.description, length: 80) %></p>
        </div>
      </div>
    </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row">

    <div class="col-md-6 col-md-offset-3 edit_user">

      <h3>Edit Profile</h3>

      <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, "Name" %>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :intro, "自我介紹" %>
            <%= f.text_area :intro, class: "form-control" %>
          </div>
          <div class="form-group">
            <%= f.label :avatar, "大頭照上傳" %>
            <%= image_tag @user.avatar if @user.avatar? %>
            <%= f.file_field :avatar %>
          </div>
          <div class="form-group">
            <%= f.submit "Update", class: "btn btn-primary" %>
            <%= link_to "Cancel", user_path(@user), class: "btn btn-default" %>
          </div>
      <% end %>

    </div>

  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-10 col-md-offset-1">

      <!-- page-header 裡面顯示個人檔案資料 -->
      <div class="page-header edit_user">

        <div class="col-md-3 col-sm-4">
          <div class="text-center">
            <%= image_tag @user.avatar, class: "img-responsive img-rounded" %>
          </div>
        </div>

        <div class="col-md-9 col-sm-8">
          <h2><%= @user.name %></h2>
          <p><strong><%= @user.email %></strong></p>
          <div><%= simple_format @user.intro %></div>
          <% if @user.email == current_user.email %>
              <%= link_to 'Edit Profile', edit_user_path(@user), class: "btn btn-primary" %>
          <% end %>
        </div>
        <div class="clearfix"></div>

      </div>

      <br>
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><strong><%= @commented_restaurants.count %></strong> 已評論餐廳</h3>
        </div>
        <div class="panel-body">
          <% @commented_restaurants.each do |restaurant| %>
              <%= link_to restaurant_path(restaurant) do %>
                  <div class="my-restaurant">
                    <div>
                      <%= image_tag restaurant.image, class: "img-responsive img-rounded" %>
                    </div>
                    <h5><%= restaurant.name %></h5>
                  </div>
              <% end %>

          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>